[package]
name = "banana_lang"
version = "0.4.1"
edition = "2021"
build = "build.rs"

[dependencies]
libloading = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"

[build-dependencies]
cbindgen = "0.26"
cc = "1.0"   # C/C++コンパイル用

[lib]
name = "banana_lang"
crate-type = ["cdylib"]      # Cから利用できるライブラリ形式
