//! エラーの発生元を`println!`で追跡するための仕組み
//!
//! エラーを作る関数は、すべて`err_factory`の中にある(以降、生成関数)。
//! エラーを返したい箇所(呼び出し元)は、次のように`err_at!`で包んで
//! 生成関数を呼ぶ。
//!
//! ```ignore
//! return crate::err_at!(self.struct_name_is_not_found());
//! ```
//!
//! すると、エラーが作られたときに次の形式で1行表示される。
//!
//! ```text
//! [parse::err] raised in: `variant_node` (crate::..::variant_node) / generated by: `variant_name_is_not_found` (crate::..::variant_name_is_not_found)
//! ```
//! - `raised in`    : エラーを発生させた関数(`err_at!`を書いた関数)
//! - `generated by` : そのエラーを生成した、`err_factory`の関数
//!
//! 環境変数`PARSE_ERR_TRACE=0`を設定すると表示しない。
//!
//! ## 生成関数を追加するとき
//! 関数の最初の行に`crate::err_generated_by!();`を書く。

use std::cell::Cell;

thread_local! {
    /// 直前の`err_at!`が記録した、呼び出し元の関数名
    static CALLER: Cell<&'static str> = const { Cell::new("<unknown>") };
}

/// 呼び出し元の関数名を記録する(`err_at!`が呼ぶ)
#[inline]
pub fn set_caller(name: &'static str) {
    CALLER.with(|c| c.set(name));
}

/// 表示してよいか(環境変数`PARSE_ERR_TRACE=0`で無効化)
fn enabled() -> bool {
    !matches!(std::env::var("PARSE_ERR_TRACE").as_deref(), Ok("0"))
}

/// `crate::a::{impl#0}::f::{{closure}}`のような完全な名前から、
/// 関数の名前(`f`)だけを取り出す
fn short_name(full: &str) -> &str {
    full.rsplit("::")
        .find(|seg| !seg.starts_with('{'))
        .unwrap_or(full)
}

/// エラーを発生させた関数と、生成した関数の名前を表示する
/// (生成関数が呼ぶ。`err_generated_by!`の中身)
///
/// 記録されている呼び出し元の名前は、ここで消す
/// (別の箇所の古い名前が表示されないようにするため)
pub fn report(generator: &'static str) {
    let caller = CALLER.with(|c| c.replace("<unknown>"));
    if enabled() {
        println!(
            "[parse::err] raised in: `{}` ({}) / generated by: `{}` ({})",
            short_name(caller),
            caller,
            short_name(generator),
            generator,
        );
    }
}

/// 今いる関数の完全な名前(`&'static str`)を返す
#[macro_export]
macro_rules! fn_name {
    () => {{
        fn __f() {}
        let n: &'static str = ::std::any::type_name_of_val(&__f);
        match n.strip_suffix("::__f") {
            Some(s) => s,
            None => n,
        }
    }};
}

/// 生成関数を呼ぶ式を包んで、今いる関数を「エラーを発生させた関数」として記録する
/// ```ignore
/// return crate::err_at!(self.some_err());
/// crate::err_at!(self.tkn_checker()).is_arrow_tkn()?;
/// ```
#[macro_export]
macro_rules! err_at {
    ($($call:tt)+) => {{
        $crate::compiler::parse::err_factory::trace::set_caller($crate::fn_name!());
        $($call)+
    }};
}

/// 生成関数の最初の行に書く。「エラーを生成した関数」を表示する
#[macro_export]
macro_rules! err_generated_by {
    () => {
        $crate::compiler::parse::err_factory::trace::report($crate::fn_name!())
    };
}
